### ISSUE TITLE
Chart version not passed when calling helm package

### ISSUE THREAD

**Issue by sebastian-garn** [entur/helm-orb#5]
Hi. I was trying you orb (command push-helm-chart-to-gcs) but there seems to be an issue about the chart version and how it is passed. Circle CI says:

```
Package Helm chart				00:00
Exit code: 1

#!/bin/bash -eo pipefail
APP_VERSION=""
VERSION="v5.0.11.1"
DEPENDENCY_UPDATE=false

[...]

CHART_LOCATION="workspace/repository/deployment/mychart"
mkdir -p build/helm
echo "Packing chart from ${CHART_LOCATION} to build/helm."
helm package ${CHART_LOCATION} --destination build/helm
Packing chart from workspace/repository/deployment/mychart to build/helm.
Error: Failed to save: no chart version specified (Chart.yaml)
Exited with code 1
```

As you can see I have passed version properly.
I assume its that line where you forgot to pass all additional parameters (like --version, --app-version) to the helm package call:

https://github.com/entur/helm-orb/blob/fbaf6ee3591eeb50a91e11d4ef315ed935a8ac9c/src/commands/push-helm-chart-to-gcs.yml#L105

Am I correct or do I use it wrong?

**Comment by olereidar** [comment]
Hello and sorry for a slow response. You are correct, it did not use any flags. 
https://github.com/entur/helm-orb/pull/6 should solve the issue. 
Thanks for notifying us
